-- Create the entries table with new rating categories
CREATE TABLE entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  attention_given smallint NOT NULL CHECK (attention_given >= 1 AND attention_given <= 5),
  compliments_given smallint NOT NULL CHECK (compliments_given >= 1 AND compliments_given <= 5),
  disrespected smallint NOT NULL CHECK (disrespected >= 1 AND disrespected <= 5),
  ignored smallint NOT NULL CHECK (ignored >= 1 AND ignored <= 5),
  loved smallint NOT NULL CHECK (loved >= 1 AND loved <= 5),
  comment text
);

-- Enable Row Level Security for the entries table
ALTER TABLE entries ENABLE ROW LEVEL SECURITY;

-- Policy: Users can insert their own entries
CREATE POLICY "Users can insert their own entries"
ON entries
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can view their own entries
CREATE POLICY "Users can view their own entries"
ON entries
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Policy: Users can update their own entries
CREATE POLICY "Users can update their own entries"
ON entries
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

-- Policy: Users can delete their own entries
CREATE POLICY "Users can delete their own entries"
ON entries
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);